name: PR Gate

on:
  pull_request:
    branches:
      - master

# Permissions needed for PR checks
permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run validation (lint, test, build)
      - name: Run validation
        run: npm run validate
        env:
          CI: true
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          BLOG_DATABASE_ID: ${{ secrets.BLOG_DATABASE_ID }}
          RECIPE_DATABASE_ID: ${{ secrets.RECIPE_DATABASE_ID }}
          INGREDIENT_DATABASE_ID: ${{ secrets.INGREDIENT_DATABASE_ID }}
          RECIPE_INGREDIENT_DATABASE_ID: ${{ secrets.RECIPE_INGREDIENT_DATABASE_ID }}

      # Comment on PR with success message
      - name: Comment on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Validation passed! All tests and linting checks completed successfully.'
            })

      # Comment on PR with failure message
      - name: Comment on PR failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Validation failed. Please check the workflow logs for details.'
            })
